### ISSUE TITLE
Allow use of existing storage accounts in cluster creation

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#121]
@eiriktsarpalis and @isaacabraham write:

> When provisioning, it should be possible to specify pre-existing storage accounts by name only. This is convenient when wanting to access already uploaded large data sets. Currently you need to supply the full connection string which btw is failing at the moment.

> We should be able to easily connect to existing storage accounts – in fact the API already supports that – there are functions like listStorageAccounts and getConnectionString – they just need to be composed together at the facade layer on the top.

**Comment by isaacabraham** [comment]
What's the error that we're seeing when supplying the connection string?

**Comment by isaacabraham** [comment]
@eiriktsarpalis You should supply the storage account name, not the connection string, to ```Management.CreateCluster```. Note that there is a limitation currently which is that the storage account currently needs to be in the same subscription as the cluster - we use this storage account not just for data access but also to store the cloud service package when deploying. FWIW I think that this is the right way to go - the storage account used when deploying shouldn't necessarily be the same one that you data resides in.

Currently it's not particularly easy to bind multiple storage accounts to MBrace - you can do it, but it's a bit of a pain because you have to supply the different store client every time you need to access the data. But I would like to see it made easier in general with MBrace to work with multiple store clients using e.g. WASB-style connections. The same that this works with e.g. HDInsight is that at deployment time you provide a set of storage accounts, all of which are then available for data access. One of them is marked as the primary / default storage account, and this is where the HDInsight internal folders are created - the equivalent for MBrace would be e.g. Vagabond assemblies and persisted CloudFlows.

**Comment by evilpepperman** [comment]
I would also like this for the service bus account.

Having mnemonically named storage/svcbus will allow for attribution.  Also convenient for persistent blob management.

**Comment by eiriktsarpalis** [comment]
This has been fixed as of MBrace.Azure 1.1. Bit late, but closing this now :-)
