### ISSUE TITLE
Separate out low-level management calls and high-level MBrace.Azure management calls

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#123]
I know we have a signature file, but we should move some of the functionality to separate modules. Trial builder for example (I wasn't even aware of this until just now - I thought we were still on Chessie), and the lower level MAML code.

**Comment by dsyme** [comment]
I don't really mind either way - I'm personally ok with one file, since the code you mention is not reused. 

The Chessie "Trial" implementation seems a bit strange -  I'd need to write up why but I suspect it would be a long discussion.  But @eiriktsarpalis plans to remove the use of trial anyway in favour of Async+Logging which is ok too.

**Comment by dsyme** [comment]
I'll close this since I think we let @eiriktsarpalis do it however he thinks is best in #124
