### ISSUE TITLE
Separation of transient and persistent MBrace storage artifacts

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#14]
MBrace currently utilises - as I understand it - cloud storage for three purposes: -

1. Transient data used for executing running processes etc., using queues, blobs and tables.
2. Persistant data e.g. logs.
3. User data e.g. CloudFiles.

Currently all of these are bundled into one storage account. It would be great if we could separate out these - particularly the first one. This would enable you to create a storage account used for the running of a particular cluster and then drop the storage account with the cluster and not lose any data except for the transient data used by the cluster.

In addition, separating out the user data from the other stuff would enable users to run MBrace on their own storage accounts without having them modified with lots of containers being created. I know that you can manually add a cloud store to a cluster, but this is again outside the "default" flow - it would good to enable this separation formally.

**Comment by dsyme** [comment]
+1

**Comment by krontogiannis** [comment]
Sure, it's just the default case that you use the same storage account for primitives and runtime state.
If you want you can register you custom cloudstore in your WorkerRole OnStart : 
```csharp
_svc = new Service(_config);
var myBlobAccount = BlobStore.Create("mycustomconnectionstring");
_svc.RegisterStoreProvider(myBlobAccount);
```
The same goes for the AtomProvider (which uses tables instead of blobs) and the ChannelProvider which uses service bus queues.

This way you can change the default accounts used by the CloudFile/Atom/Channel primitives without specifying them manually in `.CreateProcess` in client.

**Comment by isaacabraham** [comment]
OK, cool. So if we were to do that, would the StoreProvider be used for ```CloudFile``` refs? And the standard storage connection string (used in Configuration.WithStorageConnectionString) would be used for internal MBrace state?

**Comment by krontogiannis** [comment]
[Exactly](https://github.com/mbraceproject/MBrace.Azure/blob/new-core-temp/src/MBrace.Azure.Runtime/Service.fs#L94) :)

**Comment by krontogiannis** [comment]
#22
