### ISSUE TITLE
ExecutionTime can now be negative

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#32]
I just moved to MBrace 0.61-alpha on Brisk

I know MBrace is fast, but this is a bit too fast :)

  [(1, -1.2120928); (10, -2.0173713); (100, 0.9582827)]

The negative values were produced by this:

    yield (sz, job.ExecutionTime.TotalSeconds), res

**Comment by krontogiannis** [comment]
Fixed in afb31d77c2ee3ffd36b7ef2428b48c579419b78f.

Just a note: `.ExecutionTime` might be a bit inaccurate while a process is running as it subtracts your local client's utc from the process initialization time calculated in Azure (client's time might be a few seconds off).

Of course when the process completes `.ExecutionTime` is accurate because both init time and complete time are calculated on Azure.
