### ISSUE TITLE
Please review new sample

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#36]
Please take a look at this sample: https://github.com/elastacloud/mbrace-on-brisk-starter/pull/43/files#diff-ba7c1d6cb1b85eb7b732c2200b6c6b72R1

Is building new serializable abstractions like this an acceptable part of the MBrace programming model?

**Comment by eiriktsarpalis** [comment]
I think that an important aspect of defining cloud primitives, particularly
when implementation is runtime-dependent is the use of 'ResourceRegistry'.
Typically you would start with a factory pattern IFoo/IFooFactory and then
have MBrace resolve the factory dependency from the monad. For example,
cloud {
    let! factory = Workflow.Resolve<IFooFactory> ()
    return factory.Create()
}
It would be useful if MBrace.Azure could support user-supplied dependencies
in addition to the ones provided by the runtime implementation. Perhaps I
should knock together a small tutorial describing the internal continuation
APIs.

Other than that, the example looks fine. It would also work with
ISerializable or no serialization attributes. The reason we chose
DataContract for our own implementations is because it is cleaner than
field-based serialization and less error prone than ISerializable.

On Tuesday, March 10, 2015, Don Syme <notifications@github.com> wrote:

> Please take a look at this sample:
> https://github.com/elastacloud/mbrace-on-brisk-starter/pull/43/files#diff-ba7c1d6cb1b85eb7b732c2200b6c6b72R1
>
> Is building new serializable abstractions like this an acceptable part of
> the MBrace programming model?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/36>.
>


-- 
Sent from Gmail Mobile

**Comment by krontogiannis** [comment]
MBrace.Azure [supports](https://github.com/mbraceproject/MBrace.Azure/blob/603034d93560096aab9211076e5253a200135e32/src/MBrace.Azure.Runtime/Service.fs#L84) user supplied resources using
```fsharp
service.RegisterResource(new IFooFactory())
```
(Although, today, I temporarily disabled this in our appdomain branch).

Also `IFooFactory` should also be serializable.

**Comment by krontogiannis** [comment]
A little bit off-topic, but I was thinking about having registered by default the 'native' Azure Blob/Table/Queue (and maybe ServiceBus) clients using the configuration connection strings.
And provide some azure specific extensions on `Cloud` like
`Cloud.GetDefaultBlobClient()` or sth.

**Comment by eiriktsarpalis** [comment]
But this is in the server side, right? I was wondering if it were possible
to specify ad-hoc resources from the client side, provided they are
serializable.

Btw, I think that this code should include checks to verify that user
inputs do not overwrite things like the IRuntimeProvider.

On Tuesday, March 10, 2015, Kostas Rontogiannis <notifications@github.com>
wrote:

> MBrace.Azure supports
> <https://github.com/mbraceproject/MBrace.Azure/blob/603034d93560096aab9211076e5253a200135e32/src/MBrace.Azure.Runtime/Service.fs#L84>
> user supplied resources using
>
> service.RegisterResource(new IFooFactory())
>
> (Although, today, I temporarily disabled this in our appdomain branch).
>
> Also IFooFactory should also be serializable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/36#issuecomment-78122950>
> .
>


-- 
Sent from Gmail Mobile

**Comment by krontogiannis** [comment]
Yeah, server side and now with appdomains should be serializable too.
Client side registration should be [implemented](https://github.com/mbraceproject/MBrace.Azure/issues/29) at some point.

**Comment by palladin** [comment]
I can see the general purpose of this sample but I can't understand this part 
"In this case we build an abstraction over an Azure storage queue (not
+an Azure service bus queue, which is a different beast)"

**Comment by dsyme** [comment]
I've removed that comment, thanks

**Comment by dsyme** [comment]
Closing this as it has now been reviewed
