### ISSUE TITLE
Reset() prevents workers showing

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#69]
I called Reset() on my cluster. It worked (or at least it didn't crash!). However, when I now call GetWorkers() or ShowWorkers(), it does not show any workers up.

I can still submit jobs etc. and they get fulfilled by the cluster - it's just that the nodes aren't visible.

**Comment by isaacabraham** [comment]
By the way - I restarted the workers manually and then they did show up.

**Comment by krontogiannis** [comment]
I will change the heartbeats to insertOrMerge operations instead of merge, but i'm pretty sure that calling reset should be followed by manually restart of workers in most cases in order to have a fully functional worker.

Note that Reset has some optional arguments that you might want to look into (cleaning only the job queue without cleaning the other state, etc).

**Comment by dsyme** [comment]
I'm closing this since it's so old
