### ISSUE TITLE
Workers take a long time to disappear from GetWorkers list

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#87]
I down-scaled a 100 machine cluster to 1 machine.  It seemed to take 10 minutes (from 17:37 to 17:47 in wall clock time) for the workers to disappear from the active worker list.

I understand workers might not respond for a while. But 10 minutes is a very generous heartbeat signal on Azure.  It feels like 1 minute may be more reasonable?  How would it affect things to change this?  

Cheers
don

**Comment by krontogiannis** [comment]
10 minutes seemed like a good match because of this:
[Windows Azure Role Architecture](http://blogs.msdn.com/b/kwill/archive/2011/05/05/windows-azure-role-architecture.aspx)
*Host Agent lives on the Host OS and is responsible for setting up Guest OS and communicating with Guest Agent (WindowsAzureGuestAgent) in order to drive the role towards goal state and to do heartbeat checks with the guest agent.  If host agent does not receive heartbeat response for 10 minutes, host agent will restart the guest OS.*

Initially the max interval was set to 1min, but running very CPU intensive computations (~100% total cpu usage) caused workers to miss heartbeats in that interval, to seem dead in the MBrace APIs, but the worker was clearly alive in the Azure portal.

Maybe we can change this to sth in 1--5min, but the 10min seemed good to match the role's interval.

Also the heartbeat column of `ShowWorkers` is definitely a good way to check if the worker is indeed alive.

**Comment by krontogiannis** [comment]
The Brisk worker role template have been updated to declare the worker status as stopped in cases of scale down (or any graceful shutdown). So the worker is instantly removed from the list of active workers.

**Comment by isaacabraham** [comment]
Close this?
